#!/usr/bin/python
from versebg import verse
import time
import os, sys
import shutil
import site
from os.path import expanduser
from datetime import datetime
from apscheduler.scheduler import Scheduler

version = "/versebg-0.1.2-py2.7.egg/" #This is horrible

"""
Author - Greg McCoy

Date - June 28th 2015

Description - start script for versebg, checks if .versebg 
directory exists and if it doesn't makes one and copies the 
data files over to it. It then start the script on a schedule
to reload every day

"""

# Start the scheduler
sched = Scheduler()
sched.daemonic = False
sched.start()

def run():
	#journal.send("Running at " +  time.strftime('%l:%M%p %Z on %b %d, %Y'))
	verse.update()

run()
sched.add_cron_job(run, hour="1")
